// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vkjleqyttfuckdxntopm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZramxlcXl0dGZ1Y2tkeG50b3BtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5MTkzMzcsImV4cCI6MjA1NzQ5NTMzN30.BSVAP_yvGWQqzcvA9EvpWoxrPe8_5sDBaXjpkqMgAtM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);